-- Supabase schema for a multi-machine vending dashboard.
-- Demo policies allow anon read/write so ESP32 and the web client can test
-- quickly with the public publishable/anon key. For production, move writes
-- behind auth, device tokens, or Supabase Edge Functions.

create table if not exists public.machines (
  id text primary key,
  name text not null,
  location text,
  status text not null default 'offline',
  firmware_version text,
  current_credit integer not null default 0,
  cash_in_box integer not null default 0,
  total_sales integer not null default 0,
  total_revenue integer not null default 0,
  total_refunded integer not null default 0,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  machine_id text not null references public.machines(id) on delete cascade,
  slot integer not null,
  name text not null,
  price integer not null default 10000,
  stock integer not null default 0,
  capacity integer not null default 4,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  unique (machine_id, slot),
  check (slot > 0),
  check (price >= 0),
  check (stock >= 0),
  check (capacity >= 0)
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  machine_id text not null references public.machines(id) on delete cascade,
  product_slot integer not null,
  product_name text,
  unit_price integer not null,
  credit_before integer not null default 0,
  credit_after integer not null default 0,
  success boolean not null default true,
  message text,
  created_at timestamptz not null default now()
);

create table if not exists public.money_events (
  id bigint generated by default as identity primary key,
  machine_id text not null references public.machines(id) on delete cascade,
  amount integer not null,
  source text not null default 'yolo',
  raw_label text,
  confidence numeric(8, 4),
  created_at timestamptz not null default now(),
  check (amount > 0)
);

create table if not exists public.machine_events (
  id bigint generated by default as identity primary key,
  machine_id text not null references public.machines(id) on delete cascade,
  event_type text not null,
  severity text not null default 'info',
  message text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.machine_commands (
  id bigint generated by default as identity primary key,
  machine_id text not null references public.machines(id) on delete cascade,
  command_type text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  error_message text,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  check (status in ('pending', 'sent', 'done', 'error'))
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();

  if tg_table_name = 'machines' then
    if new.status in ('online', 'busy', 'error') then
      new.last_seen_at = now();
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists touch_machines_updated_at on public.machines;
create trigger touch_machines_updated_at
before update on public.machines
for each row execute function public.touch_updated_at();

drop trigger if exists touch_products_updated_at on public.products;
create trigger touch_products_updated_at
before update on public.products
for each row execute function public.touch_updated_at();

alter table public.machines enable row level security;
alter table public.products enable row level security;
alter table public.sales enable row level security;
alter table public.money_events enable row level security;
alter table public.machine_events enable row level security;
alter table public.machine_commands enable row level security;

drop policy if exists "demo all machines" on public.machines;
drop policy if exists "demo all products" on public.products;
drop policy if exists "demo all sales" on public.sales;
drop policy if exists "demo all money events" on public.money_events;
drop policy if exists "demo all machine events" on public.machine_events;
drop policy if exists "demo all machine commands" on public.machine_commands;

create policy "demo all machines" on public.machines
for all to anon using (true) with check (true);

create policy "demo all products" on public.products
for all to anon using (true) with check (true);

create policy "demo all sales" on public.sales
for all to anon using (true) with check (true);

create policy "demo all money events" on public.money_events
for all to anon using (true) with check (true);

create policy "demo all machine events" on public.machine_events
for all to anon using (true) with check (true);

create policy "demo all machine commands" on public.machine_commands
for all to anon using (true) with check (true);

create index if not exists products_machine_slot_idx on public.products(machine_id, slot);
create index if not exists sales_machine_created_idx on public.sales(machine_id, created_at desc);
create index if not exists money_events_machine_created_idx on public.money_events(machine_id, created_at desc);
create index if not exists machine_events_machine_created_idx on public.machine_events(machine_id, created_at desc);
create index if not exists machine_commands_machine_status_idx on public.machine_commands(machine_id, status, created_at desc);

insert into public.machines (id, name, location, status, firmware_version)
values ('vending-001', 'May ban hang 001', 'Phong test', 'offline', 'cloud-0.1')
on conflict (id) do update
set name = excluded.name,
    location = excluded.location;

insert into public.products (machine_id, slot, name, price, stock, capacity, enabled)
values
  ('vending-001', 1, 'San pham 1', 10000, 4, 4, true),
  ('vending-001', 2, 'San pham 2', 10000, 4, 4, true),
  ('vending-001', 3, 'San pham 3', 10000, 4, 4, true),
  ('vending-001', 4, 'San pham 4', 10000, 4, 4, true)
on conflict (machine_id, slot) do update
set name = excluded.name,
    price = excluded.price,
    stock = excluded.stock,
    capacity = excluded.capacity,
    enabled = excluded.enabled;
